#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-colorspace
Version  : 1.2
Release  : 19
URL      : http://cran.r-project.org/src/contrib/colorspace_1.2-4.tar.gz
Source0  : http://cran.r-project.org/src/contrib/colorspace_1.2-4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
BuildRequires : R-dichromat
BuildRequires : R-mvtnorm
BuildRequires : clr-R-helpers
BuildRequires : tcl

%description
No detailed description available

%prep
%setup -q -c -n colorspace

%build

%install
rm -rf %{buildroot}
export LANG=C
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --build  -l %{buildroot}/usr/lib64/R/library colorspace
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-codoc -l %{buildroot}/usr/lib64/R/library colorspace


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/colorspace/CITATION
/usr/lib64/R/library/colorspace/DESCRIPTION
/usr/lib64/R/library/colorspace/INDEX
/usr/lib64/R/library/colorspace/LICENSE
/usr/lib64/R/library/colorspace/Meta/Rd.rds
/usr/lib64/R/library/colorspace/Meta/data.rds
/usr/lib64/R/library/colorspace/Meta/hsearch.rds
/usr/lib64/R/library/colorspace/Meta/links.rds
/usr/lib64/R/library/colorspace/Meta/nsInfo.rds
/usr/lib64/R/library/colorspace/Meta/package.rds
/usr/lib64/R/library/colorspace/Meta/vignette.rds
/usr/lib64/R/library/colorspace/NAMESPACE
/usr/lib64/R/library/colorspace/NEWS
/usr/lib64/R/library/colorspace/R/colorspace
/usr/lib64/R/library/colorspace/R/colorspace.rdb
/usr/lib64/R/library/colorspace/R/colorspace.rdx
/usr/lib64/R/library/colorspace/data/Rdata.rdb
/usr/lib64/R/library/colorspace/data/Rdata.rds
/usr/lib64/R/library/colorspace/data/Rdata.rdx
/usr/lib64/R/library/colorspace/doc/hcl-colors.R
/usr/lib64/R/library/colorspace/doc/hcl-colors.Rnw
/usr/lib64/R/library/colorspace/doc/hcl-colors.pdf
/usr/lib64/R/library/colorspace/doc/index.html
/usr/lib64/R/library/colorspace/help/AnIndex
/usr/lib64/R/library/colorspace/help/aliases.rds
/usr/lib64/R/library/colorspace/help/colorspace.rdb
/usr/lib64/R/library/colorspace/help/colorspace.rdx
/usr/lib64/R/library/colorspace/help/paths.rds
/usr/lib64/R/library/colorspace/html/00Index.html
/usr/lib64/R/library/colorspace/html/R.css
/usr/lib64/R/library/colorspace/libs/colorspace.so
/usr/lib64/R/library/colorspace/libs/symbols.rds
